# Generated by Django 4.2.6 on 2023-10-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobapplicaton_jobposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
    ]
